import { NODE_TOKEN_ID_LENGTH, NODE_TOKEN_SECRET_LENGTH } from '@hopper/shared';
import { z } from 'zod';

/**
 * Schema of the daemon's configuration file (`/etc/hopper/daemon.yml`).
 *
 * This file is written by the installer or copied from the panel: it holds the
 * node secret and the JWT signing secret. It has to belong to root and be in
 * mode 0600 — the daemon refuses to start otherwise (see
 * `assertConfigFilePermissions`).
 */

const sslSchema = z
  .object({
    enabled: z.boolean().default(false),
    certificatePath: z.string().optional(),
    keyPath: z.string().optional(),
  })
  .refine((ssl) => !ssl.enabled || (ssl.certificatePath && ssl.keyPath), {
    message: 'certificatePath and keyPath are required when ssl.enabled is true',
  });

const apiSchema = z.object({
  host: z.string().default('0.0.0.0'),
  port: z.number().int().min(1).max(65535).default(8443),
  ssl: sslSchema.prefault({}),
  /** Maximum size of a file upload, in bytes. */
  uploadLimitBytes: z
    .number()
    .int()
    .positive()
    .default(1024 * 1024 * 1024),
  /**
   * Origins allowed to open a WebSocket to this daemon. Must contain the
   * panel's public URL. An empty list blocks every browser connection.
   */
  allowedOrigins: z.array(z.string()).default([]),
});

const panelSchema = z.object({
  /** Public URL of the panel, e.g. `https://panel.example.com`. */
  url: z.url(),
  /**
   * Secret shared with the panel, used to verify the signature of console JWTs
   * and signed URLs. Distinct from the node secret: the first signs tokens
   * meant for browsers, the second authenticates the panel itself.
   */
  jwtSecret: z.string().min(32),
});

const systemSchema = z.object({
  /** Root of the daemon's data. Everything else derives from it by default. */
  rootDirectory: z.string().default('/var/lib/hopper'),
  /** Server volumes, one subfolder per UUID. */
  dataDirectory: z.string().optional(),
  backupDirectory: z.string().optional(),
  /**
   * Compression format for backups.
   *
   * `gzip` by default, and it is not the most efficient choice: zstd compresses
   * a Minecraft world markedly faster, at a comparable ratio. But a `.tar.zst`
   * archive does not open without a dedicated tool — Windows Explorer does
   * nothing with it, and the user is left with a backup they cannot look
   * inside. A backup unreadable by whoever downloads it only half does its job.
   *
   * Archives already produced stay restorable and downloadable whatever this
   * setting says: the format is written into the file name.
   */
  backupCompression: z.enum(['gzip', 'zstd']).default('gzip'),
  /** Temporary archives (compression, uploads in flight). Purged at startup. */
  tmpDirectory: z.string().optional(),
  /** UID/GID applied to the servers' files on the host. */
  uid: z.number().int().nonnegative().default(988),
  gid: z.number().int().nonnegative().default(988),
  timezone: z.string().default('UTC'),
  sftp: z
    .object({
      enabled: z.boolean().default(true),
      bindAddress: z.string().default('0.0.0.0'),
      bindPort: z.number().int().min(1).max(65535).default(2022),
      /** SSH host key. Generated by the installer if absent. */
      hostKeyPath: z.string().optional(),
    })
    .prefault({}),
});

const dockerSchema = z.object({
  socket: z.string().default('/var/run/docker.sock'),
  network: z
    .object({
      /** Dedicated bridge network: isolates the servers from the default bridge. */
      name: z.string().default('hopper0'),
      /** Create the network at startup if it does not exist. */
      autoCreate: z.boolean().default(true),
      subnet: z.string().default('172.28.0.0/16'),
      gateway: z.string().default('172.28.0.1'),
      enableIpv6: z.boolean().default(false),
    })
    .prefault({}),
  /**
   * Remove unused images after a template update.
   * Off by default: on a shared host, purging someone else's images would be
   * hostile.
   */
  pruneUnusedImages: z.boolean().default(false),

  /**
   * Apply the per-server block I/O weight (`BlkioWeight`).
   *
   * Off by default because it is a host capability, not an innocuous setting:
   * under cgroup v2, `io.weight` only exists if the BFQ scheduler is active. On
   * a kernel using mq-deadline — the default on most distributions, and the
   * case with Docker Desktop — the container simply refuses to start with an
   * unreadable OCI message.
   *
   * To turn it on: `cat /sys/block/<disk>/queue/scheduler` has to mention
   * `[bfq]`.
   */
  blkioWeight: z.boolean().default(false),
});

export const daemonConfigSchema = z.object({
  debug: z.boolean().default(false),
  /** Node UUID, as shown in the panel. */
  uuid: z.uuid(),
  tokenId: z.string().length(NODE_TOKEN_ID_LENGTH),
  tokenSecret: z.string().length(NODE_TOKEN_SECRET_LENGTH),

  // `prefault` and not `default`: the value `{}` travels through the schema,
  // which recursively applies each field's default. With `default`, Zod 4 would
  // demand an already complete object.
  api: apiSchema.prefault({}),
  panel: panelSchema,
  system: systemSchema.prefault({}),
  docker: dockerSchema.prefault({}),
});

export type DaemonConfigInput = z.input<typeof daemonConfigSchema>;
export type DaemonConfig = z.infer<typeof daemonConfigSchema>;
