/**
 * The SteamCMD installation every Source dedicated server needs.
 *
 * Lifted out of the Garry's Mod template the moment a second game joined it,
 * which is what that template's own docblock asked for: `srcds_run`, the
 * anonymous depot, the `.steam/sdk32` fallback and the two checks at the end are
 * the engine's, not the game's. What stays with each game is its app id, its
 * `-game` directory, the disk it needs and the configuration file it seeds.
 *
 * Everything here was measured on app 4020 and the measurements are labelled as
 * such, because a fact about one depot is not a fact about the engine. Where a
 * finding might not carry — whether a depot ships its own `steamclient.so`, what
 * the shipped `server.cfg` contains — the script is written so that being wrong
 * about it costs nothing.
 */

export interface SteamInstall {
  /** SteamCMD application id of the **dedicated server**, never the client's. */
  appId: number;
  /** The directory `-game` names, and the one the depot must leave behind. */
  gameDir: string;
  /** Displayed in the script's own output. */
  gameName: string;
  /**
   * The `<gameDir>/cfg/server.cfg` this install seeds when it finds none.
   *
   * Passed in rather than generated, because the file is the one place a game
   * gets to explain itself to its operator, and a generated one would say
   * nothing a generated one could not say about any game.
   */
  serverCfg: string;
  /** A closing line naming where the game's own settings live. */
  epilogue: string[];
}

export function steamInstallScript(game: SteamInstall): string {
  const { appId, gameDir, gameName } = game;

  return [
    '#!/bin/bash',
    '# set -e: a failing step has to stop the installation. An install that',
    '# reports success over half a depot produces a server that exits a second',
    '# after every start, with nothing in the console to connect that back to the',
    '# download.',
    'set -euo pipefail',
    '',
    '# ---------------------------------------------------------------------',
    '# What runs this',
    '# ---------------------------------------------------------------------',
    '# Nothing below switches user, because nothing below wants another uid: the',
    '# apt-get needs root, SteamCMD runs perfectly well as root when its HOME is',
    '# writable, and the volume it writes into is chowned by the daemon after',
    '# this container is gone.',
    '#',
    '# A script that does want another uid is better off with "runuser -u steam',
    '# --" or "setpriv --reuid=... --regid=... --" than with su: those need only',
    "# the granted SETUID and SETGID, so they cannot depend on the node's audit",
    '# configuration. su does work here — measured, exit 0 under exactly the',
    '# seven capabilities the daemon grants — and docs/templates.md carries the',
    '# correction to the claim that it could not.',
    '',
    '# i386, and the dpkg line is load-bearing rather than ceremonial: without it',
    '# apt fetches no i386 package lists at all and the install below fails with',
    '# "Unable to locate package". SteamCMD ships a 32-bit bootstrap binary, so a',
    '# 64-bit Debian cannot execute it until the second architecture exists.',
    '# libstdc++6:i386 pulls libgcc-s1:i386 and libc6:i386 in with it, which is',
    "# the whole of the 32-bit runtime SteamCMD needs — the game's own 32-bit",
    "# libraries are the runtime image's problem, not this container's.",
    'dpkg --add-architecture i386',
    'apt-get update',
    'apt-get install -y --no-install-recommends ca-certificates curl tar libstdc++6:i386',
    '',
    '# In this container, not in the volume. The community scripts unpack',
    '# SteamCMD into /mnt/server/steamcmd, which leaves fifty megabytes of client',
    "# in the operator's file manager, counted against their disk quota, for a",
    '# tool the runtime image cannot run anyway. Here it is discarded with the',
    '# container and the volume holds the game alone.',
    'STEAMCMD_DIR=/opt/steamcmd',
    'mkdir -p "${STEAMCMD_DIR}"',
    '',
    '# --fail, because without it curl writes an HTTP error page into the file',
    '# and exits 0, and tar then fails on something that is not an archive with a',
    '# message about the archive rather than about the download.',
    'curl -sSL --fail -o /tmp/steamcmd.tar.gz \\',
    '  "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz"',
    'tar -xzf /tmp/steamcmd.tar.gz -C "${STEAMCMD_DIR}"',
    'rm -f /tmp/steamcmd.tar.gz',
    '',
    'if [ ! -x "${STEAMCMD_DIR}/steamcmd.sh" ]; then',
    '  echo "What was downloaded is not a SteamCMD archive." >&2',
    '  exit 1',
    'fi',
    '',
    '# ---------------------------------------------------------------------',
    '# The depot',
    '# ---------------------------------------------------------------------',
    '# A long-standing SteamCMD failure: with no steamapps/ under the install',
    '# directory it reports a disk write error instead of creating one. Every',
    '# community Steam install script creates it in advance for that reason, and',
    '# one mkdir is cheaper than an error message that blames the disk.',
    'mkdir -p /mnt/server/steamapps',
    '',
    'cd "${STEAMCMD_DIR}"',
    '',
    '# +force_install_dir BEFORE +app_update, and it is not optional.',
    '#',
    '# SteamCMD applies it to the commands that follow and not to the ones',
    '# already run, and left unsaid it installs into a directory of its own under',
    "# this container's filesystem — the layer that is deleted the moment the",
    '# installation ends. The depot would download to completion, this script',
    '# would exit 0, and the server would start on an empty volume. It is also',
    "# the directory nothing measured: the daemon's disk preflight measures the",
    '# filesystem holding the volume and names no other, so the figure declared',
    '# in installRequiredDiskBytes would have been checked against a disk the',
    '# download never touched.',
    '#',
    `# +login anonymous: app ${appId} is a public dedicated server and needs no`,
    '# account. Nothing in this template can hold a Steam password.',
    '#',
    '# The app id is written into the template rather than taken from a variable.',
    '# One template per game is the point: the readiness marker, the -game',
    "# directory and the disk figure are all this app's, and a variable app id",
    '# would make every one of them a lie for whatever else was typed into it.',
    '#',
    '# validate re-checks every file against the manifest and re-downloads what',
    '# does not match. That is what makes a reinstall a repair rather than a',
    '# gamble, and it is the whole update mechanism for this server.',
    '#',
    "# Retried, because what it is retrying is not this machine's doing.",
    '#',
    `# Measured on app ${appId}: the exact line below, in a fresh container on a`,
    '# machine with 31 GB free, answered "Connecting anonymously to Steam',
    '# Public...OK / Waiting for user info...OK / ERROR! Failed to install app',
    `# '${appId}' (Missing configuration)" and exited 8 — before one byte of depot.`,
    '# The same line, on the same machine, in another fresh container ten',
    '# minutes later, downloaded the whole thing. Steam had not handed out the',
    "# app's configuration, and nothing here can make it. What the panel can do",
    '# is stop turning a passing Steam mood into a failed installation somebody',
    '# has to notice and start again.',
    '#',
    '# Three attempts and not thirty: a real failure — a wrong app id, a full',
    '# volume — fails the same way every time, and is better reported in a',
    '# minute than in an hour. A retry costs little either, since Steam keeps',
    '# what it has already staged under steamapps/downloading.',
    'STEAMCMD_LOG=/tmp/steamcmd.log',
    'STEAMCMD_ATTEMPTS=3',
    '',
    'steam_update() {',
    '  ./steamcmd.sh +force_install_dir /mnt/server +login anonymous \\',
    `    +app_update ${appId} validate +quit`,
    '}',
    '',
    '# tee, so the operator goes on watching the download in their console while',
    '# the last attempt is also kept for the diagnosis below. pipefail, set at',
    '# the top, is what makes this test steamcmd rather than tee.',
    'attempt=1',
    'until steam_update 2>&1 | tee "${STEAMCMD_LOG}"; do',
    '  if [ "${attempt}" -ge "${STEAMCMD_ATTEMPTS}" ]; then',
    '    echo "" >&2',
    '',
    '    if grep -q "Missing configuration" "${STEAMCMD_LOG}"; then',
    '      echo "Steam accepted the anonymous login and then refused to hand out" >&2',
    `      echo "the configuration for app ${appId}. Nothing on this machine decides" >&2`,
    '      echo "that, and it comes and goes. Reinstall in a few minutes: the same" >&2',
    '      echo "command has been watched to work unchanged." >&2',
    '    elif grep -q "state is 0x202" "${STEAMCMD_LOG}"; then',
    '      echo "SteamCMD stopped with state 0x202. Measured on this depot with" >&2',
    '      echo "1.9 GB free, that is what running out of room looks like: the" >&2',
    '      echo "download stages into steamapps/downloading before the files land," >&2',
    '      echo "so the install wants roughly twice the finished size free." >&2',
    '    elif grep -q "No subscription" "${STEAMCMD_LOG}"; then',
    `      echo "Steam says this account does not own app ${appId}. The login here" >&2`,
    '      echo "is anonymous, so the app is not one of the freely installable" >&2',
    '      echo "dedicated servers — an app id for a game client, most often." >&2',
    '    else',
    '      echo "SteamCMD failed three times. Its own last words are above." >&2',
    '    fi',
    '',
    '    exit 1',
    '  fi',
    '',
    '  echo ""',
    '  echo "SteamCMD gave up (attempt ${attempt} of ${STEAMCMD_ATTEMPTS}). Retrying in 30s."',
    '  echo ""',
    '  attempt=$((attempt + 1))',
    '  sleep 30',
    'done',
    '',
    '# ---------------------------------------------------------------------',
    '# The Steam client library, and what it is really insuring against',
    '# ---------------------------------------------------------------------',
    '# A fallback, and on some depots one that is never reached. Measured on app',
    '# 4020: that depot ships its own steamclient.so at the install root, 45 MiB',
    '# of it, and srcds_run exports LD_LIBRARY_PATH=".:bin:..." before exec-ing',
    '# the binary, so SteamAPI_Init finds that one first and says so — "Loaded',
    "# local 'steamclient.so' OK\". With /mnt/server/.steam masked out entirely",
    '# the server still logs in, is assigned its gameserver Steam ID and turns',
    '# VAC on.',
    '#',
    '# The copy stays because the fallback is real and because whether a depot',
    '# ships that file is a property of the depot, not of the engine — this',
    "# script runs against several and has measured one. Masking the depot's own",
    '# copy makes srcds print "dlopen failed trying to load: steamclient.so" and',
    "# then \"Loaded '/home/container/.steam/sdk32/steamclient.so' OK. (First",
    "# tried local 'steamclient.so')\" — it logs in either way. 47 MiB of the",
    '# volume buys a login that cannot be lost to one file at the root of the',
    '# game tree, on an engine whose Steam login is also its readiness marker.',
    '#',
    '# sdk64 is deliberately NOT written beside it. srcds_run picks its binary in',
    '# detectcpu(), which on Linux is "HL=./srcds_linux" with no 64-bit branch at',
    '# all, so these templates can only ever start the 32-bit server — and a',
    '# depot that ships linux64/steamclient.so does so for whoever starts the',
    "# 64-bit binary directly. A second 44 MiB copy in the operator's volume for",
    '# a path nothing here takes is not insurance, it is weight.',
    '#',
    '# HOME is /home/container in the runtime image, and the volume is mounted',
    '# there, so ~/.steam here is /mnt/server/.steam. That equivalence is the',
    '# reason the image pins HOME at all, and .github/workflows/source-image.yml',
    '# asserts it on every build.',
    'if [ ! -f "${STEAMCMD_DIR}/linux32/steamclient.so" ]; then',
    '  echo "SteamCMD left no linux32/steamclient.so to install." >&2',
    '  exit 1',
    'fi',
    '',
    '# The path written out rather than assembled, because this string is a',
    '# contract with the runtime image — where the volume is mounted, and what',
    '# HOME is set to — and a contract is worth being able to grep for.',
    'mkdir -p /mnt/server/.steam/sdk32',
    'cp -f "${STEAMCMD_DIR}/linux32/steamclient.so" /mnt/server/.steam/sdk32/steamclient.so',
    '',
    '# ---------------------------------------------------------------------',
    '# What the startup command is going to need',
    '# ---------------------------------------------------------------------',
    '# Checked rather than trusted: set -e catches a steamcmd that failed, and',
    '# cannot catch one that succeeded somewhere other than where the startup',
    '# command will look. This is the only place those two paths can be compared,',
    '# and they have to agree.',
    'cd /mnt/server',
    '',
    'if [ ! -x srcds_run ]; then',
    '  echo "SteamCMD reported success but left no executable srcds_run in" >&2',
    '  echo "/mnt/server. The startup command names ./srcds_run and would fail" >&2',
    '  echo "at the first start." >&2',
    '  exit 1',
    'fi',
    '',
    `if [ ! -d ${gameDir} ]; then`,
    `  echo "SteamCMD reported success but left no ${gameDir}/ directory, which" >&2`,
    `  echo "is what -game ${gameDir} names." >&2`,
    '  exit 1',
    'fi',
    '',
    '# ---------------------------------------------------------------------',
    "# The operator's own files",
    '# ---------------------------------------------------------------------',
    '# Everything from here down runs only when it finds nothing worth keeping,',
    '# and that rule is what makes this script safe to run again. It has to be:',
    '# a reinstall is the only way to update a Steam server, so an operator who',
    '# keeps their server current runs this on a volume full of their work every',
    '# few weeks. app_update leaves files it does not own alone, so addons, data',
    '# and anything uploaded survive by themselves; what needs the guard is',
    '# anything this script writes.',
    '#',
    '# The published eggs for these games get this wrong in a way worth naming,',
    '# since they are the scripts most people arrive here having used: they',
    '# truncate cfg/server.cfg on every run. Under a panel where reinstalling',
    '# *is* updating, that silently throws away the hostname, the password and',
    '# every custom line the operator has added, at the moment they were being',
    '# careful.',
    `SERVER_CFG=${gameDir}/cfg/server.cfg`,
    '',
    '# "Has content", not "exists", and the difference is the whole guard.',
    '# Measured on app 4020: the depot ships garrysmod/cfg/server.cfg itself —',
    '# four bytes, CR LF CR LF — so a test for the file alone matched on a fresh',
    '# install and this block never ran once: every server came up on an empty',
    '# config, and the console said it was keeping an existing file the operator',
    '# had never written. grep for one non-whitespace character is what tells a',
    "# depot's placeholder from a file somebody has edited, and it does that",
    '# whether or not this particular depot ships one.',
    '#',
    '# Seeding it is safe against the update path, which is the thing worth',
    '# checking before writing into a file the manifest owns: an edited',
    '# server.cfg was put through a full "+app_update 4020 validate" — 6.87 GB',
    '# re-verified, "Success! App \'4020\' fully installed" — and came back',
    '# untouched, as did a .cfg the depot has never heard of and a directory',
    '# under garrysmod/addons.',
    'if [ -f "${SERVER_CFG}" ] && grep -q "[^[:space:]]" "${SERVER_CFG}"; then',
    '  echo "Keeping the existing ${SERVER_CFG}."',
    'else',
    `  mkdir -p ${gameDir}/cfg`,
    '',
    '  # A quoted heredoc: nothing in the body is expanded, so the file lands',
    '  # exactly as written even where it contains characters a shell would read.',
    '  cat > "${SERVER_CFG}" <<\'CFG\'',
    game.serverCfg,
    'CFG',
    '',
    '  echo "Seeded ${SERVER_CFG} with a hostname you should change."',
    'fi',
    '',
    `echo "${gameName} installed."`,
    `echo "Update it by reinstalling: that re-runs app_update ${appId} validate,"`,
    `echo "which repairs the game files and leaves your own ${gameDir} files alone."`,
    'echo ""',
    ...game.epilogue.map((line) => `echo ${JSON.stringify(line)}`),
    'echo ""',
    'echo "This server has no Steam game-server login token and no RCON: both"',
    'echo "need a credential the panel cannot yet store out of sight. It logs in"',
    'echo "to Steam anonymously, which works."',
  ].join('\n');
}
